import sqlite3

import discord
from discord.ext import commands


class Me(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    async def me(self, ctx):
        await ctx.message.delete()
        conn = sqlite3.connect('dbs/registered.db')
        cur = conn.cursor()
        cur.execute(f'''SELECT discord_id FROM data WHERE discord_id = {ctx.message.author.id}''')
        res = cur.fetchone()
        if res is None:
            await ctx.send('User Not Found')
        else:
            cur.execute(f'''SELECT nation_name FROM data WHERE discord_id = {ctx.message.author.id}''')
            nationname = str(cur.fetchall()[0])
            cur.execute(f'''SELECT leader_name FROM data WHERE discord_id = {ctx.message.author.id}''')
            leadername = str(cur.fetchall()[0])
            cur.execute(f'''SELECT nation_link FROM data WHERE discord_id = {ctx.message.author.id}''')
            nationlink = str(cur.fetchall()[0])
            cur.execute(f'''SELECT cities FROM data WHERE discord_id = {ctx.message.author.id}''')
            cities = str(cur.fetchall()[0])
            cur.execute(f'''SELECT offensive_wars FROM data WHERE discord_id = {ctx.message.author.id}''')
            offensive = str(cur.fetchall()[0])
            cur.execute(f'''SELECT defensive_wars FROM data WHERE discord_id = {ctx.message.author.id}''')
            defensive = str(cur.fetchall()[0])
            cur.execute(f'''SELECT avg_infra FROM data WHERE discord_id = {ctx.message.author.id}''')
            average = str(cur.fetchall()[0])
            cur.execute(f'''SELECT last_active FROM data WHERE discord_id = {ctx.message.author.id}''')
            lastactive = str(cur.fetchall()[0])
            cur.execute(f'''SELECT alliance_name FROM data WHERE discord_id = {ctx.message.author.id}''')
            alliancename = str(cur.fetchall()[0])
            cur.execute(f'''SELECT alliance_position FROM data WHERE discord_id = {ctx.message.author.id}''')
            allianceposition = str(cur.fetchall()[0])
            cur.execute(f'''SELECT alliance_link FROM data WHERE discord_id = {ctx.message.author.id}''')
            alliancelink = str(cur.fetchall()[0])
            cur.execute(f'''SELECT beige_turns FROM data WHERE discord_id = {ctx.message.author.id}''')
            beigeturns = str(cur.fetchall()[0])
            cur.execute(f'''SELECT vacation_mode_turns FROM data WHERE discord_id = {ctx.message.author.id}''')
            vacationmode = str(cur.fetchall()[0])
            cur.execute(f'''SELECT color FROM data WHERE discord_id = {ctx.message.author.id}''')
            color = str(cur.fetchall()[0])
            cur.execute(f'''SELECT score FROM data WHERE discord_id = {ctx.message.author.id}''')
            score = str(cur.fetchall()[0])
            cur.execute(f'''SELECT soldiers FROM data WHERE discord_id = {ctx.message.author.id}''')
            soldiers = str(cur.fetchall()[0])
            cur.execute(f'''SELECT tanks FROM data WHERE discord_id = {ctx.message.author.id}''')
            tanks = str(cur.fetchall()[0])
            cur.execute(f'''SELECT aircraft FROM data WHERE discord_id = {ctx.message.author.id}''')
            aircraft = str(cur.fetchall()[0])
            cur.execute(f'''SELECT ships FROM data WHERE discord_id = {ctx.message.author.id}''')
            ships = str(cur.fetchall()[0])
            cur.execute(f'''SELECT missiles FROM data WHERE discord_id = {ctx.message.author.id}''')
            missiles = str(cur.fetchall()[0])
            cur.execute(f'''SELECT nukes FROM data WHERE discord_id = {ctx.message.author.id}''')
            nukes = str(cur.fetchall()[0])
            cur.execute(f'''SELECT nation_flag FROM data WHERE discord_id = {ctx.message.author.id}''')
            flag = str(cur.fetchall()[0])
            remove_this = "()'',"
            for rt in remove_this:
                nationname = nationname.replace(rt, "")
                leadername = leadername.replace(rt, "")
                nationlink = nationlink.replace(rt, "")
                cities = cities.replace(rt, "")
                offensive = offensive.replace(rt, "")
                defensive = defensive.replace(rt, "")
                average = average.replace(rt, "")
                lastactive = lastactive.replace(rt, "")
                alliancename = alliancename.replace(rt, "")
                allianceposition = allianceposition.replace(rt, "")
                alliancelink = alliancelink.replace(rt, "")
                beigeturns = beigeturns.replace(rt, "")
                vacationmode = vacationmode.replace(rt, "")
                beigeturns = beigeturns.replace(rt, "")
                color = color.replace(rt, "")
                score = score.replace(rt, "")
                soldiers = soldiers.replace(rt, "")
                tanks = tanks.replace(rt, "")
                aircraft = aircraft.replace(rt, "")
                ships = ships.replace(rt, "")
                missiles = missiles.replace(rt, "")
                nukes = nukes.replace(rt, "")
                flag = flag.replace(rt, "")
            embed = discord.Embed(title=f'{leadername} Nation', color=discord.Colour.from_rgb(58, 194, 243))
            embed.add_field(name='Nation Name', value=f'[{nationname}]({nationlink})', inline=True)
            embed.add_field(name='Cities', value=cities, inline=True)
            embed.add_field(name='Average Infrastructure', value=average, inline=True)
            embed.add_field(name='Last Active', value=f'{lastactive} Days ago', inline=True)
            embed.add_field(name='Vacation Turns', value=vacationmode, inline=True)
            embed.add_field(name='Beige Turns', value=beigeturns, inline=True)
            embed.add_field(name='Alliance Name', value=f'[{alliancename}]({alliancelink})', inline=True)
            embed.add_field(name='Position', value=allianceposition, inline=True)
            embed.add_field(name='Color Bloc', value=color, inline=True)
            embed.add_field(name='Score', value=score, inline=True)
            embed.add_field(name='Soldiers', value=(format(int(soldiers), ",")), inline=True)
            embed.add_field(name='Tanks', value=(format(int(tanks), ",")), inline=True)
            embed.add_field(name='Aircraft', value=(format(int(aircraft), ",")), inline=True)
            embed.add_field(name='Ships', value=(format(int(ships), ",")), inline=True)
            embed.add_field(name='Missiles', value=missiles, inline=True)
            embed.add_field(name='Nukes', value=nukes, inline=True)
            embed.add_field(name='Offensive Wars', value=offensive, inline=True)
            embed.add_field(name='Defensive Wars', value=defensive, inline=True)
            embed.set_thumbnail(url=flag)
            await ctx.send(embed=embed)

    @me.error
    async def me_error(self, ctx, error):
        if isinstance(error, commands.CommandError):
            await ctx.message.delete()
            await ctx.send(f'{error}')


def setup(bot):
    bot.add_cog(Me(bot))
